# Generated by Django 2.0 on 2022-11-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.BooleanField(choices=[(1, 'Si'), (0, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='BinaryQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='binaryanswers',
            name='binaryQuestions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.BinaryQuestions'),
        ),
    ]
