# Generated by Django 2.0 on 2022-11-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sortedPreference', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceVoting',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=100)),
                ('preferenceQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.PreferenceQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='preferenceresponse',
            name='responseOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ResponseOption'),
        ),
        migrations.AddField(
            model_name='preferencequestion',
            name='preferenceVoting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.PreferenceVoting'),
        ),
    ]
